# Generated by Django 3.1.3 on 2021-02-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='consumer_id',
            field=models.CharField(max_length=64),
        ),
    ]
