# Generated by Django 3.1.3 on 2021-02-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_auto_20210212_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.CharField(max_length=64)),
                ('latency_proxy', models.IntegerField()),
                ('latency_gateway', models.IntegerField()),
                ('latency_request', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='request',
        ),
    ]
